-- ==============================================================================
-- DEVBUG TRACKER - DATABASE SCHEMA & RESET SCRIPT
-- ==============================================================================

-- 0. Reset / Clean Existing Tables & Sequences (Fresh Reset)
DROP TABLE IF EXISTS public.attachments CASCADE;
DROP TABLE IF EXISTS public.bug_items CASCADE;
DROP TABLE IF EXISTS public.projects CASCADE;

-- 1. Create Projects Table (Identity starts from 1)
CREATE TABLE public.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    uuid UUID DEFAULT gen_random_uuid() UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE NOT NULL,
    description TEXT,
    color VARCHAR(20) DEFAULT '#6366f1',
    repository_url TEXT,
    tech_stack TEXT[] DEFAULT '{}',
    package_manager VARCHAR(50) DEFAULT 'npm',
    test_command TEXT DEFAULT 'npm test',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Bug Items Table (Identity starts from 1)
CREATE TABLE public.bug_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    project_id BIGINT REFERENCES public.projects(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    environment VARCHAR(255),
    status VARCHAR(50) DEFAULT 'open' CHECK (status IN ('open', 'in_progress', 'resolved', 'closed')),
    severity VARCHAR(50) DEFAULT 'medium' CHECK (severity IN ('critical', 'high', 'medium', 'low')),
    investigation_state VARCHAR(50) DEFAULT 'unconfirmed' CHECK (investigation_state IN ('unconfirmed', 'reproduced', 'root_cause_isolated', 'fix_in_progress', 'fix_blocked', 'verified')),
    reproduction_reliability VARCHAR(50) DEFAULT 'untested' CHECK (reproduction_reliability IN ('untested', 'deterministic', 'intermittent', 'cannot_reproduce')),
    fix_hint TEXT,
    suspected_files TEXT[] DEFAULT '{}',
    confirmed_files TEXT[] DEFAULT '{}',
    root_cause TEXT,
    failed_attempts JSONB DEFAULT '[]'::jsonb,
    branch_name VARCHAR(255),
    base_commit_sha VARCHAR(100),
    resolved_commit VARCHAR(100),
    stack_trace TEXT,
    steps_to_reproduce TEXT,
    expected_result TEXT,
    actual_result TEXT,
    resolved_at TIMESTAMPTZ,
    "order" INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create Attachments Table (Identity starts from 1)
CREATE TABLE public.attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    bug_item_id BIGINT REFERENCES public.bug_items(id) ON DELETE CASCADE,
    file_path TEXT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_type VARCHAR(100) NOT NULL,
    file_size BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create API Keys Table for MCP / External Agent Access
CREATE TABLE public.api_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    key_hash VARCHAR(255) NOT NULL UNIQUE,
    key_prefix VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    last_used_at TIMESTAMPTZ
);

-- 5. Enable Row Level Security (RLS)
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bug_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.api_keys ENABLE ROW LEVEL SECURITY;

-- 6. Create RLS Policies (Allow Authenticated Admin full access)
CREATE POLICY "Allow authenticated users all on projects" ON public.projects
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Allow authenticated users all on bug_items" ON public.bug_items
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Allow authenticated users all on attachments" ON public.attachments
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Allow authenticated users all on api_keys" ON public.api_keys
    FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 6. Setup Supabase Storage Bucket for screenshots
INSERT INTO storage.buckets (id, name, public, allowed_mime_types, file_size_limit) 
VALUES ('bug-attachments', 'bug-attachments', true, ARRAY['image/png', 'image/jpeg', 'image/webp', 'image/gif'], 10485760)
ON CONFLICT (id) DO UPDATE SET 
    allowed_mime_types = EXCLUDED.allowed_mime_types,
    file_size_limit = EXCLUDED.file_size_limit;

-- Storage policies
CREATE POLICY "Public Access for bug-attachments" ON storage.objects
    FOR SELECT TO public USING (bucket_id = 'bug-attachments');

CREATE POLICY "Authenticated users can upload to bug-attachments" ON storage.objects
    FOR INSERT TO authenticated WITH CHECK (bucket_id = 'bug-attachments');

CREATE POLICY "Authenticated users can delete from bug-attachments" ON storage.objects
    FOR DELETE TO authenticated USING (bucket_id = 'bug-attachments');

-- 7. Initial Seed Data
INSERT INTO public.projects (name, slug, description, color, repository_url, tech_stack, test_command)
VALUES 
    ('E-Commerce Web', 'e-commerce-web', 'Online store frontend & checkout flow', '#6366f1', 'https://github.com/example/ecommerce', ARRAY['Next.js', 'React', 'TypeScript', 'Stripe'], 'npm test'),
    ('Auth Service API', 'auth-service-api', 'OAuth2 and JWT authentication microservice', '#ec4899', 'https://github.com/example/auth-api', ARRAY['Node.js', 'Express', 'PostgreSQL', 'JWT'], 'npm run test:auth'),
    ('Mobile App (Flutter)', 'mobile-app-flutter', 'Cross-platform customer mobile application', '#10b981', 'https://github.com/example/mobile-app', ARRAY['Flutter', 'Dart'], 'flutter test')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.bug_items (project_id, title, description, environment, status, severity, investigation_state, fix_hint, suspected_files, stack_trace, steps_to_reproduce, expected_result, actual_result, "order")
VALUES 
    (1, 'Payment gateway webhook drops signature verification on Stripe live mode', 'Stripe webhook returns 500 error when receiving checkout.session.completed event due to missing endpoint secret in production env.', 'Production / API Gateway', 'open', 'critical', 'root_cause_isolated', 'Check STRIPE_WEBHOOK_SECRET in production env variables and webhook handler construction.', ARRAY['app/api/webhooks/stripe/route.ts', 'lib/stripe.ts'], 'SignatureVerificationException: No signatures found matching the expected signature for payload\n  at Stripe\\Webhook::constructEvent(Webhook.php:45)\n  at App\\Http\\Controllers\\StripeController->handle(StripeController.php:19)', '1. Trigger test checkout session.\n2. Receive webhook event payload.\n3. Observe 500 status code in logs.', 'Webhook returns 200 OK and marks order as paid.', '500 Server Error and order remains pending.', 0),
    (2, 'JWT Token expiry does not invalidate active refresh tokens', 'When user password is reset, existing refresh tokens can still generate valid access tokens for 7 days.', 'Staging / Auth Service v2', 'in_progress', 'high', 'reproduced', 'Invalidate token family on password change by incrementing token_version in user table.', ARRAY['src/services/JwtService.ts', 'src/controllers/AuthController.ts'], 'TokenExpiredException: Token has expired\n  at App\\Services\\JwtService->refresh(JwtService.ts:88)', '1. Request password reset.\n2. Submit new password.\n3. Send previous refresh token to /api/auth/refresh.', 'Refresh token should be revoked immediately on password change.', 'Token issues a new valid access token.', 1),
    (3, 'Dark mode flash of unstyled content on initial page load', 'White screen flickers for ~150ms before dark theme class is applied to root HTML element on cold visit.', 'Chrome 122 / macOS Ventura', 'resolved', 'low', 'verified', 'Add blocking inline theme script in app/layout.tsx before body loads.', ARRAY['app/layout.tsx', 'components/ThemeProvider.tsx'], null, '1. Clear browser cache and localStorage.\n2. Visit website with dark mode enabled in OS.\n3. Notice brief white flash.', 'Smooth dark background without flash.', 'White flash before styles initialize.', 2);

-- 8. Migration Snippet for Existing Databases (If already deployed):
-- ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS tech_stack TEXT[] DEFAULT '{}';
-- ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS package_manager VARCHAR(50) DEFAULT 'npm';
-- ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS test_command TEXT DEFAULT 'npm test';
-- ALTER TABLE public.bug_items ADD COLUMN IF NOT EXISTS investigation_state VARCHAR(50) DEFAULT 'unconfirmed' CHECK (investigation_state IN ('unconfirmed', 'reproduced', 'root_cause_isolated', 'fix_in_progress', 'fix_blocked', 'verified'));
-- ALTER TABLE public.bug_items ADD COLUMN IF NOT EXISTS reproduction_reliability VARCHAR(50) DEFAULT 'untested' CHECK (reproduction_reliability IN ('untested', 'deterministic', 'intermittent', 'cannot_reproduce'));
-- ALTER TABLE public.bug_items ADD COLUMN IF NOT EXISTS fix_hint TEXT;
-- ALTER TABLE public.bug_items ADD COLUMN IF NOT EXISTS suspected_files TEXT[] DEFAULT '{}';
-- ALTER TABLE public.bug_items ADD COLUMN IF NOT EXISTS confirmed_files TEXT[] DEFAULT '{}';
-- ALTER TABLE public.bug_items ADD COLUMN IF NOT EXISTS root_cause TEXT;
-- ALTER TABLE public.bug_items ADD COLUMN IF NOT EXISTS failed_attempts JSONB DEFAULT '[]'::jsonb;
-- ALTER TABLE public.bug_items ADD COLUMN IF NOT EXISTS branch_name VARCHAR(255);
-- ALTER TABLE public.bug_items ADD COLUMN IF NOT EXISTS base_commit_sha VARCHAR(100);
-- ALTER TABLE public.bug_items ADD COLUMN IF NOT EXISTS resolved_commit VARCHAR(100);

-- 9. (Optional) Default Admin User Seed via SQL
-- You can run this if you want to create the admin user directly in SQL Editor:
-- INSERT INTO auth.users (
--     instance_id,
--     id,
--     aud,
--     role,
--     email,
--     encrypted_password,
--     email_confirmed_at,
--     raw_app_meta_data,
--     raw_user_meta_data,
--     created_at,
--     updated_at
-- ) VALUES (
--     '00000000-0000-0000-0000-000000000000',
--     gen_random_uuid(),
--     'authenticated',
--     'authenticated',
--     'admin@devbug.local',
--     crypt('password', gen_salt('bf')),
--     NOW(),
--     '{"provider":"email","providers":["email"]}',
--     '{}',
--     NOW(),
--     NOW()
-- ) ON CONFLICT (email) DO NOTHING;
