#!/usr/bin/env node

/**
 * DevBug Tracker - Interactive Database Setup Wizard
 * Helps users configure either Supabase Cloud or Local Self-Hosted PostgreSQL on first clone.
 */

import readline from 'node:readline'
import fs from 'node:fs'
import path from 'node:path'
import { execSync } from 'node:child_process'

const envLocalPath = path.resolve('.env.local')

function ask(questionText) {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  })

  return new Promise((resolve) => {
    rl.question(questionText, (answer) => {
      rl.close()
      resolve(answer.trim())
    })
  })
}

async function main() {
  console.log('\n======================================================')
  console.log('   DevBug Tracker - Database Initialization Setup     ')
  console.log('======================================================\n')
  console.log('Select the database backend you want to use:')
  console.log('  [1] Supabase Cloud (Managed PostgreSQL - Recommended / Quick)')
  console.log('  [2] Self-Hosted Local PostgreSQL / Docker (Local-first)\n')

  const choice = await ask('Your choice (1 or 2) [default: 1]: ') || '1'

  let supabaseUrl = ''
  let anonKey = ''
  let serviceRoleKey = ''
  const appUrl = 'http://localhost:3000'

  if (choice === '1') {
    console.log('\n--- Setup Supabase Cloud ---')
    console.log('1. Create a project on https://supabase.com')
    console.log('2. Open SQL Editor -> execute the entire content of "supabase-schema.sql"')
    console.log('3. Enter credentials from Project Settings -> API:\n')

    while (!supabaseUrl) {
      supabaseUrl = await ask('Project URL (e.g. https://xyz.supabase.co): ')
    }
    while (!anonKey) {
      anonKey = await ask('anon public API key: ')
    }
    while (!serviceRoleKey) {
      serviceRoleKey = await ask('service_role secret key: ')
    }
  } else {
    console.log('\n--- Setup Self-Hosted Local PostgreSQL (Docker) ---')
    console.log('Checking Docker availability...')

    let hasDocker = false
    try {
      execSync('docker --version', { stdio: 'ignore' })
      hasDocker = true
      console.log(' Docker daemon detected on your system.')
    } catch {
      console.log(' Docker not detected or inactive.')
      console.log('You can still use Supabase CLI if installed (supabase start).')
    }

    supabaseUrl = (await ask('Local Supabase/PostgreSQL URL [default: http://127.0.0.1:54321]: ')) || 'http://127.0.0.1:54321'
    anonKey = await ask('Local anon key [default: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM0MTI4MDB9.dummy_anon_key]: ') || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM0MTI4MDB9.dummy_anon_key'
    serviceRoleKey = await ask('Local service_role key [default: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzQxMjgwMH0.dummy_service_role_key]: ') || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzQxMjgwMH0.dummy_service_role_key'
  }

  // Write to .env.local
  const envContent = `# Auto-generated by npm run setup
NEXT_PUBLIC_SUPABASE_URL=${supabaseUrl}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${anonKey}
SUPABASE_SERVICE_ROLE_KEY=${serviceRoleKey}
NEXT_PUBLIC_APP_URL=${appUrl}

# Optional SMTP Settings for email OTP
SMTP_HOST=smtp.gmail.com
SMTP_PORT=465
SMTP_SECURE=true
SMTP_USER=
SMTP_PASS=
SMTP_FROM="DevBug Tracker <no-reply@devbug-tracker.local>"
`

  fs.writeFileSync(envLocalPath, envContent, 'utf8')
  console.log(`\n Configuration successfully saved to: ${envLocalPath}`)

  const runSeed = await ask('\nDo you want to run the default admin seed (admin@devbug.io / 123456) now? (Y/n): ')
  if (runSeed.toLowerCase() !== 'n') {
    try {
      console.log('\nRunning database seed...')
      execSync('node --env-file=.env.local scripts/seed.mjs', { stdio: 'inherit' })
    } catch (err) {
      console.warn('\n⚠️ Failed to run automatic seed. Ensure supabase-schema.sql has been executed on the database.')
    }
  }

  console.log('\n======================================================')
  console.log('   DATABASE SETUP COMPLETED!')
  console.log('   Run development server: npm run dev')
  console.log('======================================================\n')
}

main().catch((err) => {
  console.error('\nSetup error encountered:', err.message)
  process.exit(1)
})
